### ISSUE TITLE
Python Error: FileNotFoundError when trying to open a custom gateway file

### ISSUE THREAD

**Issue by classimo69** [jina-ai/gptdeploy#37]
Hi, I am finding an error after the sets of microservices are generated.
From the log, it also doesnt seem that custom_gateway.py was ever created in the directory.

Thank you so much for what you've created this is incredibly cool! 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/gptdeploy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/cli.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/cli.py", line 74, in generate
    generator.generate(path)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/options/generate/generator.py", line 283, in generate
    self.generate_playground(microservice_name, final_version_path)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/options/generate/generator.py", line 175, in generate_playground
    with open(custom_gateway_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/C:UsersUserHorizonLuna/DcaBotBacktesterExecutor8446662/0_ccxt_pandas_numpy/v4/gateway/custom_gateway.py'
```

**Comment by r-glebov** [comment]
Yep, the same issue occurs to me. MacOS Ventura, Macbook M1 pro

**Comment by florian-hoenicke** [comment]
I pushed a new version and tested it. It should work now. Just update to the latest.

**Comment by florian-hoenicke** [comment]
pip install -U gptdeploy

**Comment by florian-hoenicke** [comment]
And thanks, everyone! This is the feedback we need to fix such things fast. Means a lot to me ❤️

**Comment by classimo69** [comment]
thank you kindly, I am happy to help out/test
