### ISSUE TITLE
Only one microservice in folder error

### ISSUE THREAD

**Issue by classimo69** [jina-ai/gptdeploy#38]
Hi! I get this error after running 

`gptdeploy` run --path /Users/etc..

```

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/gptdeploy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/cli.py", line 38, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/cli.py", line 93, in deploy
    Deployer().deploy(path)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/options/deploy/deployer.py", line 7, in deploy
    validate_folder_is_correct(microservice_path)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/options/__init__.py", line 31, in validate_folder_is_correct
    raise ValueError(f'Path {microservice_path} needs to contain only one folder. Please make sure that you only have one microservice in this folder.')
ValueError: Path /Users/x/Downloads/GPTDeploy/`HorizonLuna` needs to contain only one folder. Please make sure that you only have one microservice in this folder.
```

**Comment by theholymath** [comment]
Same problem ... Tried all combinations of directory path.

**Comment by florian-hoenicke** [comment]
Hi, thanks for reporting ❤️ 
I just tried with the latest version and for me it is working.
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/11627845/233789164-6c90e33c-ce47-4865-aa27-013bea2e42b3.png">

But I guess currently the validation is too strict. In case there is something else in the generated folders, it will break.
We need to be more flexible here.
So yes. Deleting .DS_Store and other possible folders will do the trick here for now.

**Comment by florian-hoenicke** [comment]
I made a release now.
Just:
pip install -U gptdeploy
