### ISSUE TITLE
bug: OS Error for Filename Syntax on Windows

### ISSUE THREAD

**Issue by MR-Alex42** [jina-ai/gptdeploy#44]
```
Traceback (most recent call last):
  File "D:\Programme\gptdeploy\gptdeploy.py", line 5, in <module>
    main()
  File "D:\Programme\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Programme\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Programme\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Programme\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Programme\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Programme\gptdeploy\src\cli.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "D:\Programme\gptdeploy\src\cli.py", line 74, in generate
    generator.generate(path)
  File "D:\Programme\gptdeploy\src\options\generate\generator.py", line 289, in generate
    self.generate_microservice(microservice_path, microservice_name, packages, num_approach)
  File "D:\Programme\gptdeploy\src\options\generate\generator.py", line 87, in generate_microservice
    os.makedirs(MICROSERVICE_FOLDER_v1)
  File "D:\Programme\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\Programme\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'D:\\Programme\\gptdeploy\\microservice\\AnimalDetectorExecutor258302\\0_"TensorFlow Object Detection API"_"OpenCV"'
```

Happens when OpenCV is involved.

**Comment by florian-hoenicke** [comment]
Thanks! on mac and linux, these filenames are allowed but on windows it is breaking. I will fix it!

**Comment by florian-hoenicke** [comment]
More people have issues on windows. 
We have to tackle this.
https://www.reddit.com/r/softwarearchitecture/comments/12tz7wj/comment/jha7r2x/?utm_source=share&utm_medium=web2x&context=3
@JoanFM Can we push out a new core version?

**Comment by JoanFM** [comment]
Why does it have to do with jina core?

**Comment by JoanFM** [comment]
I do not ser any jina core related code in the stacktrace here

**Comment by florian-hoenicke** [comment]
oh sorry, yes that is the wrong issue. I will link you to the other one
