### ISSUE TITLE
bug: charmap codec utf-8

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/gptdeploy#49]
When using windows, we get the following error when running the service.
Setting PYTHONIOENCODING='utf-8' as recommended in https://docs.jina.ai/get-started/install/windows/ does not work

Process Process-2:
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hoenicke\jina\gptdeploy\venv\Lib\site-packages\jina\orchestrate\pods\container.py", line 217, in run
    logger = JinaLogger(name, **log_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hoenicke\jina\gptdeploy\venv\Lib\site-packages\jina\logging\logger.py", line 142, in __init__
    self.add_handlers(log_config, **context_vars)
  File "C:\Users\hoenicke\jina\gptdeploy\venv\Lib\site-packages\jina\logging\logger.py", line 203, in add_handlers
    config = JAML.load(fp)
             ^^^^^^^^^^^^^
  File "C:\Users\hoenicke\jina\gptdeploy\venv\Lib\site-packages\jina\jaml\__init__.py", line 174, in load
    r = yaml.load(stream, Loader=get_jina_loader_with_runtime(runtime_args))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hoenicke\jina\gptdeploy\venv\Lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "C:\Users\hoenicke\jina\gptdeploy\venv\Lib\site-packages\jina\jaml\helper.py", line 115, in _get_loader
    return JinaLoader(stream, runtime_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hoenicke\jina\gptdeploy\venv\Lib\site-packages\jina\jaml\helper.py", line 96, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\hoenicke\jina\gptdeploy\venv\Lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\hoenicke\jina\gptdeploy\venv\Lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\hoenicke\jina\gptdeploy\venv\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 254: character maps to <undefined>
WARNI… printhelloexecutor4715887/rep-0@17932                [04/23/23 00:09:34]
       <jina.orchestrate.pods.container.ContainerPod object                    
       at 0x00000276139DFDD0> timeout after waiting for                        
       600000ms, if your executor takes time to load, you                      
       may increase --timeout-ready           
```

**Comment by florian-hoenicke** [comment]
fyi @JoanFM

**Comment by JoanFM** [comment]
how can I reproduce the issue? and how do u set the env var?

**Comment by florian-hoenicke** [comment]
@JoanFM I just tried, but it is still the same issue

**Comment by florian-hoenicke** [comment]
Here is some code to reproduce the issue:
```
os.environ['PYTHONIOENCODING'] = 'utf-8'
os.environ['PYTHONUTF8'] = '1'
os.environ['PYTHONLEGACYWINDOWSSTDIO'] = 'utf-8'
with open('x.x', 'w') as f:
    f.write('😋 ')
```

without settint the encoding, it is not working under windows

**Comment by JoanFM** [comment]
> Here is some code to reproduce the issue:
> 
> ```
> os.environ['PYTHONIOENCODING'] = 'utf-8'
> os.environ['PYTHONUTF8'] = '1'
> os.environ['PYTHONLEGACYWINDOWSSTDIO'] = 'utf-8'
> with open('x.x', 'w') as f:
>     f.write('😋 ')
> ```
> 
> without setting the encoding, it is not working under windows

This is not the way to test. All these env vars must be passed before the script is run. Once the Python Interpreter starts, this env vars must already be set, therefore this test is not valid.

**Comment by JoanFM** [comment]
Check the first answer here

https://stackoverflow.com/questions/50933194/how-do-i-set-the-pythonutf8-environment-variable-to-enable-utf-8-encoding-by-def

**Comment by florian-hoenicke** [comment]
But we can not tell the user to setup those variables before running gptdeploy. This would not be a good interface. Instead, our code must handle this

**Comment by JoanFM** [comment]
when installing this package, u can edit their bash script.

**Comment by JoanFM** [comment]
Can we please first verify that these env vars work?

**Comment by florian-hoenicke** [comment]
@MR-Alex42 you are right. This was missed out.
Here is a fix that even works without setting the environment variables.
https://github.com/jina-ai/gptdeploy/pull/58
So we don't need to add it to the documentation
