### ISSUE TITLE
entity was not found - gptdeploy deploy

### ISSUE THREAD

**Issue by classimo69** [jina-ai/gptdeploy#59]
Hi, running on a mac, m1

```
 To log
Calling _send_request_with_retry failed, retry attempt 1/3. Error:
Exception('RequestedEntityNotFoundError: No such executor:
auth0-unified-448f11965ce142b6/JiraConfluenceChatbotExecutor3773376 session_id:
1fa79ee2-e29a-11ed-a6ad-1e00e234f659')
Calling _send_request_with_retry failed, retry attempt 2/3. Error:
Exception('RequestedEntityNotFoundError: No such executor:
auth0-unified-448f11965ce142b6/JiraConfluenceChatbotExecutor3773376 session_id:
1fa79ee2-e29a-11ed-a6ad-1e00e234f659')
Calling _send_request_with_retry failed, retry attempt 3/3. Error:
Exception('RequestedEntityNotFoundError: No such executor:
auth0-unified-448f11965ce142b6/JiraConfluenceChatbotExecutor3773376 session_id:
1fa79ee2-e29a-11ed-a6ad-1e00e234f659')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/gptdeploy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/cli.py", line 39, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/cli.py", line 84, in run
    Runner().run(path)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/options/run/runner.py", line 10, in run
    run_locally(executor_name, latest_version_path)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/src/apis/jina_cloud.py", line 204, in run_locally
    with flow:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jina/orchestrate/orchestrator.py", line 14, in __enter__
    return self.start()
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jina/orchestrate/flow/builder.py", line 33, in arg_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jina/orchestrate/flow/base.py", line 1830, in start
    self.enter_context(deployment)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 505, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jina/orchestrate/orchestrator.py", line 14, in __enter__
    return self.start()
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jina/orchestrate/deployments/__init__.py", line 1017, in start
    self.enter_context(self.shards[shard_id])
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 505, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jina/orchestrate/deployments/__init__.py", line 112, in __enter__
    self._pods.append(PodFactory.build_pod(_args).start())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jina/orchestrate/pods/factory.py", line 39, in build_pod
    cargs.uses = HubIO(_hub_args).pull()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hubble/executor/hubio.py", line 1259, in pull
    executor, from_cache = HubIO.fetch_meta(
                           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hubble/executor/helper.py", line 657, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hubble/executor/hubio.py", line 1074, in fetch_meta
    resp = _send_request_with_retry(pull_url, json=payload, headers=req_header)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hubble/executor/helper.py", line 116, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hubble/executor/hubio.py", line 1051, in _send_request_with_retry
    raise Exception(
Exception: RequestedEntityNotFoundError: No such executor: auth0-unified-448f11965ce142b6/JiraConfluenceChatbotExecutor3773376 session_id: 1fa79ee2-e29a-11ed-a6ad-1e00e234f659
```

**Comment by KAWAKO-in-GAYHUB** [comment]
same issue for me

```
gptdeploy run --path /Users/kawako/microservice
Run a jina flow locally
⠸ Fetching auth0-unified-448f11965ce142b6/EquationSolverExecutor6517380 from 
Jina Hub ...🔐 You are not logged in to Jina AI. To log in, use jina auth login or set env 
Calling _send_request_with_retry failed, retry attempt 1/3. Error: 
Exception('RequestedEntityNotFoundError: No such executor: 
auth0-unified-448f11965ce142b6/EquationSolverExecutor6517380 session_id: 
11b4d7ee-e305-11ed-b939-de8d7425afaa')
Calling _send_request_with_retry failed, retry attempt 2/3. Error: 
Exception('RequestedEntityNotFoundError: No such executor: 
auth0-unified-448f11965ce142b6/EquationSolverExecutor6517380 session_id: 
11b4d7ee-e305-11ed-b939-de8d7425afaa')
Calling _send_request_with_retry failed, retry attempt 3/3. Error: 
Exception('RequestedEntityNotFoundError: No such executor: 
auth0-unified-448f11965ce142b6/EquationSolverExecutor6517380 session_id: 
11b4d7ee-e305-11ed-b939-de8d7425afaa')
Traceback (most recent call last):
  File "/Users/kawako/opt/anaconda3/bin/gptdeploy", line 8, in <module>
    sys.exit(main())
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/src/cli.py", line 39, in wrapper
    return func(*args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/src/cli.py", line 84, in run
    Runner().run(path)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/src/options/run/runner.py", line 10, in run
    run_locally(executor_name, latest_version_path)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/src/apis/jina_cloud.py", line 204, in run_locally
    with flow:
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/orchestrator.py", line 14, in __enter__
    return self.start()
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/flow/builder.py", line 33, in arg_wrapper
    return func(self, *args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 1830, in start
    self.enter_context(deployment)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/contextlib.py", line 448, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/orchestrator.py", line 14, in __enter__
    return self.start()
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/deployments/__init__.py", line 1008, in start
    self.enter_context(self.shards[shard_id])
  File "/Users/kawako/opt/anaconda3/lib/python3.9/contextlib.py", line 448, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/deployments/__init__.py", line 112, in __enter__
    pod = PodFactory.build_pod(_args).start()
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/pods/factory.py", line 39, in build_pod
    cargs.uses = HubIO(_hub_args).pull()
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/hubble/executor/hubio.py", line 1259, in pull
    executor, from_cache = HubIO.fetch_meta(
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/hubble/executor/helper.py", line 657, in wrapper
    result = func(*args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/hubble/executor/hubio.py", line 1074, in fetch_meta
    resp = _send_request_with_retry(pull_url, json=payload, headers=req_header)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/hubble/executor/helper.py", line 116, in wrapper
    return func(*args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/hubble/executor/hubio.py", line 1051, in _send_request_with_retry
    raise Exception(
Exception: RequestedEntityNotFoundError: No such executor: auth0-unified-448f11965ce142b6/EquationSolverExecutor6517380 session_id: 11b4d7ee-e305-11ed-b939-de8d7425afaa
(base) kawako@KAWAKOdeMacBook-Pro ~ % docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
(base) kawako@KAWAKOdeMacBook-Pro ~ % docker images
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
(base) kawako@KAWAKOdeMacBook-Pro ~ % gptdeploy run --path /Users/kawako/microservice
Run a jina flow locally
⠙ Fetching auth0-unified-448f11965ce142b6/EquationSolverExecutor6517380 from 
Jina Hub ...🔐 You are not logged in to Jina AI. To log in, use jina auth login or set env 
Calling _send_request_with_retry failed, retry attempt 1/3. Error: 
Exception('RequestedEntityNotFoundError: No such executor: 
auth0-unified-448f11965ce142b6/EquationSolverExecutor6517380 session_id: 
356fea48-e305-11ed-b5ea-de8d7425afaa')
Calling _send_request_with_retry failed, retry attempt 2/3. Error: 
Exception('RequestedEntityNotFoundError: No such executor: 
auth0-unified-448f11965ce142b6/EquationSolverExecutor6517380 session_id: 
356fea48-e305-11ed-b5ea-de8d7425afaa')
Calling _send_request_with_retry failed, retry attempt 3/3. Error: 
Exception('RequestedEntityNotFoundError: No such executor: 
auth0-unified-448f11965ce142b6/EquationSolverExecutor6517380 session_id: 
356fea48-e305-11ed-b5ea-de8d7425afaa')
Traceback (most recent call last):
  File "/Users/kawako/opt/anaconda3/bin/gptdeploy", line 8, in <module>
    sys.exit(main())
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/src/cli.py", line 39, in wrapper
    return func(*args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/src/cli.py", line 84, in run
    Runner().run(path)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/src/options/run/runner.py", line 10, in run
    run_locally(executor_name, latest_version_path)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/src/apis/jina_cloud.py", line 204, in run_locally
    with flow:
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/orchestrator.py", line 14, in __enter__
    return self.start()
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/flow/builder.py", line 33, in arg_wrapper
    return func(self, *args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/flow/base.py", line 1830, in start
    self.enter_context(deployment)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/contextlib.py", line 448, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/orchestrator.py", line 14, in __enter__
    return self.start()
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/deployments/__init__.py", line 1008, in start
    self.enter_context(self.shards[shard_id])
  File "/Users/kawako/opt/anaconda3/lib/python3.9/contextlib.py", line 448, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/deployments/__init__.py", line 112, in __enter__
    pod = PodFactory.build_pod(_args).start()
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/jina/orchestrate/pods/factory.py", line 39, in build_pod
    cargs.uses = HubIO(_hub_args).pull()
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/hubble/executor/hubio.py", line 1259, in pull
    executor, from_cache = HubIO.fetch_meta(
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/hubble/executor/helper.py", line 657, in wrapper
    result = func(*args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/hubble/executor/hubio.py", line 1074, in fetch_meta
    resp = _send_request_with_retry(pull_url, json=payload, headers=req_header)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/hubble/executor/helper.py", line 116, in wrapper
    return func(*args, **kwargs)
  File "/Users/kawako/opt/anaconda3/lib/python3.9/site-packages/hubble/executor/hubio.py", line 1051, in _send_request_with_retry
    raise Exception(
Exception: RequestedEntityNotFoundError: No such executor: auth0-unified-448f11965ce142b6/EquationSolverExecutor6517380 session_id: 356fea48-e305-11ed-b5ea-de8d7425afaa
```

my device is macbook pro, m1, 16g

**Comment by florian-hoenicke** [comment]
Thanks for reporting this issue! @classimo69 and @KAWAKO-in-GAYHUB
could you please send us the code that got generated? That way we can better find out what happened.
