### ISSUE TITLE
bug: Invalid Literal Error when running Microservice locally on Windows

### ISSUE THREAD

**Issue by MR-Alex42** [jina-ai/gptdeploy#60]
gptdeploy run --path D:\Programme\gptdeploy\microservice

Traceback (most recent call last):
  File "D:\Programme\gptdeploy\gptdeploy.py", line 5, in <module>
    main()
  File "D:\Programme\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Programme\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Programme\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Programme\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Programme\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Programme\gptdeploy\src\cli.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "D:\Programme\gptdeploy\src\cli.py", line 83, in run
    Runner().run(path)
  File "D:\Programme\gptdeploy\src\options\run\runner.py", line 7, in run
    validate_folder_is_correct(microservice_path)
  File "D:\Programme\gptdeploy\src\options\__init__.py", line 43, in validate_folder_is_correct
    latest_version_path = get_latest_version_path(microservice_path)
  File "D:\Programme\gptdeploy\src\options\__init__.py", line 27, in get_latest_version_path
    latest_version_path = get_latest_folder(latest_approach_path, max_fn=version_max_fn)
  File "D:\Programme\gptdeploy\src\options\__init__.py", line 16, in get_latest_folder
    return max_fn([os.path.join(path, f) for f in listdir_no_hidden(path) if os.path.isdir(os.path.join(path, f))])
  File "D:\Programme\gptdeploy\src\options\__init__.py", line 19, in version_max_fn
    version_list = [int(path.split('/')[-1].replace('v', '')) for path in path_list]
  File "D:\Programme\gptdeploy\src\options\__init__.py", line 19, in <listcomp>
    version_list = [int(path.split('/')[-1].replace('v', '')) for path in path_list]
ValueError: invalid literal for int() with base 10: 'D:\\Programme\\gptdeploy\\microserice\\DeepComplimentExecutor7439463\\0_gpt_3_5_turbo_api\\1'

**Comment by florian-hoenicke** [comment]
Thanks. Can you check if this pr fixes the issue?
https://github.com/jina-ai/gptdeploy/pull/58

**Comment by MR-Alex42** [comment]
Did use the latest version. The error still occurs.

**Comment by florian-hoenicke** [comment]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/11627845/234244149-bd7a338b-1dec-478f-9404-bce4d8e8763d.png">
I did not find this in the current code base.
Can you do 
```
pip install gptdeploy -U
```
to force update?

**Comment by MR-Alex42** [comment]
This is solved.
