### ISSUE TITLE
windows path to file issue

### ISSUE THREAD

**Issue by HaniehCloud** [jina-ai/gptdeploy#8]
`Traceback (most recent call last):
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hubble\__init__.py", line 131, in show_hint
    print(
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\__init__.py", line 74, in print
    return write_console.print(*objects, sep=sep, end=end)
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 1672, in print
    with self:
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 2039, in _check_buffer
    write(text)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f510' in position 0: character maps to <undefined>
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hbaza\OneDrive\Documents\git projects\gptdeploy\gptdeploy.py", line 4, in <module>
    main()
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\hbaza\OneDrive\Documents\git projects\gptdeploy\src\cli.py", line 26, in create
    executor_factory.create(description, num_approaches, output_path, test)
  File "C:\Users\hbaza\OneDrive\Documents\git projects\gptdeploy\src\executor_factory.py", line 291, in create
    executor_path = self.debug_executor(output_path, packages, description, test)
  File "C:\Users\hbaza\OneDrive\Documents\git projects\gptdeploy\src\executor_factory.py", line 181, in debug_executor
    log_hubble = push_executor(previous_executor_path)
  File "C:\Users\hbaza\OneDrive\Documents\git projects\gptdeploy\src\jina_cloud.py", line 47, in push_executor
    req_header = get_request_header()
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hubble\executor\helper.py", line 226, in get_request_header
    auth_token = get_token()
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hubble\__init__.py", line 109, in get_token
    token = show_hint(interactive)
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\hubble\__init__.py", line 150, in show_hint
    print(f'Unknown error: {ex}')
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\__init__.py", line 74, in print
    return write_console.print(*objects, sep=sep, end=end)
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 1672, in print
    with self:
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "C:\Users\hbaza\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rich\console.py", line 2039, in _check_buffer
    write(text)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f510' in position 0: character maps to <undefined>
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***
PS C:\Users\hbaza\OneDrive\Documents\git projects\gptdeploy>`

Path encoding issue in windows

**Comment by florian-hoenicke** [comment]
Thanks again, the issue is now resolved.
